---

- name: creates directory
  file: 
    path: ~/build
    state: directory

- name: Extract the zipped artifact
  unarchive:
    src: /home/jenkins/workspace/petclinic/artifact.tar.gz
    dest: ~/build/
    
- name: Verify that artifact has been extracted
  debug:
    msg: "Artifact has been extracted successfully"

- name: Run Spring Boot application
  become: true
  shell: nohup java -jar spring-petclinic-3.0.0.jar --spring.profiles.active=mysql &
  args:
    chdir: ~/build/libs/
